packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  esbuild: true
  keccak: true
  lefthook: true
  secp256k1: true
overrides:
  elliptic: ^6.6.1
  secp256k1: ^5.0.1
  "@ethersproject/providers>ws": ^7.5.11
  jsdom>ws: ^8.21.3
  image-size: ^2.0.3
